### ISSUE TITLE
parallelize() is broken

### ISSUE THREAD

**Issue by gfiedler** [funkwerk/jenkins-workflow#7] opened 2016-10-06 12:26 UTC
The following Jenkinsfile

```
jobs = ['foo', 'bar']
parallelize jobs, { node {
  print it
} }
```

has this log

```
[Pipeline] parallel
[Pipeline] [foo] { (Branch: foo)
[Pipeline] [bar] { (Branch: bar)
[Pipeline] [foo] node
[Pipeline] [bar] node
[foo] Running on node-1
[Pipeline] [foo] {
[bar] Running on node-2
[Pipeline] [bar] {
[Pipeline] [foo] echo
[foo] bar
[Pipeline] [foo] }
[Pipeline] [bar] echo
[bar] bar
[Pipeline] [bar] }
[Pipeline] [foo] // node
[Pipeline] [foo] }
[Pipeline] [bar] // node
[Pipeline] [bar] }
[Pipeline] // parallel
[Pipeline] End of Pipeline
Finished: SUCCESS
```

The job `bar` is executed twice.

**Comment by lindt** [comment] 2017-02-15 01:23
it's a bit better now, but yes,waiting forJenkins to fix their groovy handling

**Comment by FeepingCreature** [comment] 2018-10-24 05:49
This seems to have gotten fixed by itself at some point.

Can't reproduce.

**Closed as completed by FeepingCreature** 2018-10-24 05:49 UTC
